### ISSUE TITLE
[BUG] Tabbing to Auto-Complete Objects

### ISSUE THREAD

**Issue by InValidFire** [bridge-core/bridge.#100] opened 2019-10-31 16:24 UTC
**Summary**
When you tab to auto-complete from selection in the dropdown list, it will add both the intended item and the incomplete text entered.

**To Reproduce**
1. Go to a file where autocompletion works. (ie a block's .json file)
2. Start typing an object you want to add, do not complete it
3. Using arrow keys, select an option from the suggested list
4. Press TAB to auto complete
4. Observe results

**Observed behavior**
You will see both the selected item and the text you started typing get added to the file.
(ie. Started typing 'mine' and tab completed to 'minecraft:loot', you will see 'min' and 'minecraft:loot' added)

This appears to happen everywhere autocompletion is enabled.
**Expected behavior**
Only the tab completed item should be added to the file.
(ie. Started typing 'min' and tab completed to 'minecraft:loot', you will see only 'minecraft:loot' added)

**Screenshots / File Attachments**
If applicable, add screenshots to help explain your problem or upload files to help us reproduce the bug.

PREPARING TO AUTO COMPLETE
![image](https://user-images.githubusercontent.com/32578904/67965255-18daa200-fbd8-11e9-8508-312e460e91b2.png)

AFTER TAB COMPLETION
![image](https://user-images.githubusercontent.com/32578904/67965275-24c66400-fbd8-11e9-9dfe-fb248ade3ff2.png)

**Platform (please complete the following information):**
 - OS: Windows 10
 - App Version: 0.13.17

**Additional context**
This issue only appears if autocompletion is done through the keyboard only. Clicking an option with the mouse has the intended result.

**Comment by solvedDev** [comment] 2019-12-20 10:56
After further investigation #100 and #101 seem to be connected to an issue with my UI framework with no way for me to currently fix it. Looks like the issue is about to get fixed though 🤞

**Comment by solvedDev** [comment] 2019-12-20 10:56
Didn't mean to close it, oops :D

**Closed** 2020-01-22 11:35 UTC
Labels: Bug, Fixed
