### ISSUE TITLE
[BUG] BP animation keyframe time stamp changes in Bridge editor, but saved correctly in actual file

### ISSUE THREAD

**Issue by Cubh** [bridge-core/bridge.#252] opened 2020-08-06 00:11 UTC
**Summary**
With a BP animation created and edited in Bridge, the time stamps in the timeline will reset to the number of their position in the array upon saving, if the number entered was an integer (with or without decimals).

If I enter "0.2", or "4.5" it stays. But if I enter "4", or "4.0", it will reset to "0" if the time stamp is the first in the timeline, "1" if it is the second, etc.

**To Reproduce**
1. Create a Behavior Pack animation
2. In an animation in the file, add a timeline
3. In the timeline array, add a timestamp (no event or command needed)
4. Enter an integer for the timestamp
5. Save

**Observed behavior**
The time stamp value changes on its own to "0" if the time stamp is first in the timeline, "1" if second, "2" if third, etc.
But the value is correctly saved in the actual file if you check by opening it in another editor.
**Expected behavior**
The time stamp keeps the value entered in the editor.

**Platform (please complete the following information):**
 - OS: Windows 10
 - App Version: 1.7.1

**Comment by solvedDev** [comment] 2020-08-06 09:20
Thanks a lot for the very detailed report!
I am closing this issue since it is a duplicate of #230 though :)

**Closed by solvedDev** 2020-08-06 09:20 UTC
Labels: Bug
