### ISSUE TITLE
Problem when creating new item [BUG]

### ISSUE THREAD

**Issue by LionLight95** [bridge-core/bridge.#349] opened 2021-05-23 14:03 UTC
Basically when I create an item the "format version" isn't with the "minecraft:item" any fixes available

**Comment by solvedDev** [comment] 2021-05-23 14:05
Thanks for the report! 
@Joelant05 can you take a look? Sounds like it might have been caused by our latest data update

**Comment by Joelant05** [comment] 2021-05-23 14:06
I'll take a look soon 👍

**Comment by solvedDev** [comment] 2021-05-25 17:35
Closed by 4439017aeaa2e3b9868f61120594c10c758734ea

**Closed by solvedDev** 2021-05-25 17:35 UTC
Labels: Bug
