### ISSUE TITLE
[BUG]When adding a new file and pressing CTRL+Backspace, stuff in the background gets deleted

### ISSUE THREAD

**Issue by HerrNamenlos123** [bridge-core/bridge.#234] opened 2020-07-12 19:26 UTC
**Summary**
When you add a new file or something similar so that a new window pops up over the current json file, you can enter the name of the new file. When you then press CTRL and Backspace, like when you want to delete the entire word at once, instead of deleting the word in the name field, elements from the json file in the background get deleted.

**To Reproduce**
Open a file so the content is displayed, then create a new file and when entering the name, press CTRL and Backspace.

**Observed behavior**
Instead of the name file, content from the file in the background gets deleted.
**Expected behavior**
The last word or entire content of the name field should be deleted.

**Platform (please complete the following information):**
 - OS: Windows 10
 - App Version: v1.6.0

**Comment by solvedDev** [comment] 2020-07-12 19:41
Thanks for your report. This seems to be a duplicate of #191 though :)

**Closed** 2020-07-12 19:41 UTC
Labels: Bug, Duplicate

**Comment by HerrNamenlos123** [comment] 2020-07-12 20:00
You're right, this is what i meant.
I did check if this topic already exists but i must have missed it...

**Comment by solvedDev** [comment] 2020-07-12 20:05
No worries, I'd rather haves duplicated report than non at all :)
